# ĐẠI SỐ TUYẾN TÍNH

In [55]:
import numpy as np

In [56]:
a = np.array([[1,2,3],
              [10,20,30],
              [9,8,7]])

In [57]:
b = np.array([[5,6],
              [3,4],
              [1,2]])

In [58]:
# a (3x3) X (3x2)
c = a.dot(b) # dot = tích vô hướng
c

array([[ 14,  20],
       [140, 200],
       [ 76, 100]])

In [59]:
 #c[1,1] =
1*5 + 2*3 + 3*1 # Hàng  nhân với cột

14

a.dot(b) = A @ B

In [60]:
a @ b

array([[ 14,  20],
       [140, 200],
       [ 76, 100]])

## Dot Product Example

In [61]:
#Number of jars sold
np.random.seed(0)
sales_amount = np.random.randint(20,size = (5,3))

In [62]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [63]:
#Create weekly_sales DataFrame
import pandas as pd
import numpy as np

In [64]:
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                                        columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [65]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [66]:
# Create a price array
prices = np.array([5, 7, 11])

In [67]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"],
                             columns=["ALmond Butter", "Peanut Butter", "Cashew Butter"])


In [68]:
butter_prices

ALmond Butter  Peanut Butter  Cashew Butter
Price              5              7             11

In [69]:
weekly_sales.shape, butter_prices.T.shape

((5, 3), (3, 1))

In [70]:
total_prices = weekly_sales.dot(butter_prices.T)

ValueError: matrices are not aligned