In [1]:
import numpy as np

np.sort uses an QUICKSORT algorithm

In [2]:
x = np.array([2,1,10,3,5])

In [3]:
np.sort(x)

array([ 1,  2,  3,  5, 10])

In [4]:
#Func argsort
np.argsort(x)

array([1, 0, 3, 4, 2], dtype=int64)

In [5]:
# Hiển thị Vị trí của các phần tử 

### Sorting along rows or columns Sắp xếp theo cột hoặc hàng

In [6]:
np.random.seed(42)
matA = np.random.randint(0,10,size = (4,6))

In [7]:
matA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [8]:
np.sort(matA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [9]:
np.sort(matA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])